
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from scipy.optimize import curve_fit
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from scipy.stats import linregress
import os
import calibration_methods
from calibration_methods import *
from flightanalysis_methods import *
import inspect

DATA_DIR = '/Users/emmamartignoni/Downloads/3 Scint CW'
RESULTS_DIR = '/Users/emmamartignoni/HERA-Research/CW-analysis/Results'


ten_day_run = process_run(f'{DATA_DIR}/AHD032.csv',
                            [f'{DATA_DIR}/55_top.txt', f'{DATA_DIR}/57_Mid.txt', f'{DATA_DIR}/58_Bot.txt'],
                            results_dir=os.path.join(RESULTS_DIR, 'ten_day_run'),
                            moyal_fit_ranges=[(44, 70), (46, 74), (42, 70)],
                            twodim_hist_args={'cbar_max': 200}) # meant to be run as a guess and check method. Pick random mV values to start and, once the plots are generated by the pipeline, look back at a rate spectrum the code creates (mip_normalized.png) and decide ranges for the Moyal fit. Enter here and re-run

print(f"MPVs for the 10 day run: {ten_day_run[2].mpv_per_scint}")
